### ISSUE TITLE
seNorge2018_2021.nc is missing the 31st of December

### ISSUE THREAD

**Issue by kristss** [metno/seNorge_docs#4]
The seNorge2018_2021.nc file in the archive for last year (senorge/seNorge_2018/Archive/seNorge2018_2021.nc) has a time dimension of 364. It looks like it is the 31st of December that is missing.

**Comment by cristianlussana** [comment]
Thanks. I'll have a look at it.

**Comment by cristianlussana** [comment]
I have replaced the file. Now the file senorge/seNorge_2018/Archive/seNorge2018_2021.nc has the correct number of time steps.
Thanks again for your feedback.
