### ISSUE TITLE
seNorge2018_2022.nc disappears from time to time

### ISSUE THREAD

**Issue by frafra** [metno/seNorge_docs#5]
Hi,
it looks that the `seNorge2018_2022.nc` file has just been deleted and reappeared after half an hour. WMS endpoint went down too. I guess it could be that the file is being updated, but if that is the case, it would be better to generate a temporary file with a different name and then replace the old file with the new file once the computation is finished, to reduce the downtime.

**Comment by cristianlussana** [comment]
Hi Francesco,
thanks for your feedback. Good point, I'll have a look and let you know if I change the process of file creation
Best Regards, Cristian

**Comment by cristianlussana** [comment]
Hi, now it should be better. The new file seNorge2018_2022.nc replaces the old one with minimal downtime.
Cristian
