### ISSUE TITLE
seNorge2018_2022.nc is missing a day

### ISSUE THREAD

**Issue by kristss** [metno/seNorge_docs#7]
Hi,
it looks like the file in the archive for last year, seNorge2018_2022.nc v. 22.09, is missing a day (time dimension is 364). Without looking for the specific date, I suppose it could be the 31st of December as in issue #4 that was resolved last year for seNorge2018_2021.nc v. 21.

**Comment by cristianlussana** [comment]
Hi,
Thanks for reporting. I am working on it. Should be ready soon (today)

**Comment by cristianlussana** [comment]
the file is ready and it should be fine now.
Thanks!

**Comment by kristss** [comment]
Thank you for the quick feedback! I downloaded the new file and works fine now.
