### ISSUE TITLE
GDAL cannot recognize axis unit

### ISSUE THREAD

**Issue by frafra** [metno/seNorge_docs#9]
Hi,
this is a regression we discovered before the summer, that affects previously generated data. We had no issue in December 2022, then files got updated (last time on 2023-06-22, according to the thredds server). Now GDAL has issues in recognizing the unit meters.

```
$ gdallocationinfo -wgs84 -b 1 NETCDF:"/vsicurl/https://thredds.met.no/thredds/fileServer/senorge/seNorge_2018/Archive/seNorge2018_2022.nc":rr 10.407 63.431
ERROR 1: Unhandled X/Y axis unit meters. SRS will ignore axis unit and be likely wrong.
Report:
  Location: (345P,958L)
  Band 1:
    Value: 0.740000009536743
 gdallocationinfo -wgs84 -b 1 NETCDF:"/vsicurl/https://thredds.met.no/thredds/fileServer/senorge/seNorge_snow/sd/sd_2022.nc":snow_depth 10.407 63.431
ERROR 1: Unhandled X/Y axis unit meters. SRS will ignore axis unit and be likely wrong.
Report:
  Location: (345P,958L)
  Band 1:
    Value: 10.1000003814697
```

It could be great if you could just check the consistency of the updated files with gdal before they get released. I made a small script for that as an example:

```bash
#!/bin/bash

set -eu

lon=10.407
lat=63.431

echo "# seNorge GDAL test"
echo
echo "## Test info"
echo "Date: $(date)"
echo "Using $(gdalinfo --version)"
echo
echo "## Results"

for resource in \
  NETCDF:"/vsicurl/https://thredds.met.no/thredds/fileServer/senorge/seNorge_snow/swe/swe_2024.nc":snow_water_equivalent \
  NETCDF:"/vsicurl/https://thredds.met.no/thredds/fileServer/senorge/seNorge_2018/Archive/seNorge2018_2024.nc":rr \
  NETCDF:"/vsicurl/https://thredds.met.no/thredds/fileServer/senorge/seNorge_2018/aggregated_products/tg/seNorge2018_tg_normal_1991_2020_yearly.nc":tg
do
  echo "### $resource"
  result="$(gdallocationinfo -wgs84 -b 1 "$resource" $lon $lat 2>&1 >/dev/null || true)"
  if [ -z "$result" ]
  then
    echo "✅ Check passed"
  else
    echo "❌ Check failed"
    echo '```'
    echo "$result"
    echo '```'
  fi
  echo
done
```

That is the current result:

# seNorge GDAL test

## Test info
Date: Mon Oct  7 02:02:07 PM CEST 2024
Using GDAL 3.8.4, released 2024/02/08

### NETCDF:/vsicurl/https://thredds.met.no/thredds/fileServer/senorge/seNorge_snow/swe/swe_2024.nc:snow_water_equivalent
❌ Check failed
```
ERROR 1: Unhandled X/Y axis unit meters. SRS will ignore axis unit and be likely wrong.
```

### NETCDF:/vsicurl/https://thredds.met.no/thredds/fileServer/senorge/seNorge_2018/Archive/seNorge2018_2024.nc:rr
❌ Check failed
```
ERROR 1: Unhandled X/Y axis unit meters. SRS will ignore axis unit and be likely wrong.
```

### NETCDF:/vsicurl/https://thredds.met.no/thredds/fileServer/senorge/seNorge_2018/aggregated_products/tg/seNorge2018_tg_normal_1991_2020_yearly.nc:tg
❌ Check failed
```
ERROR 1: Unhandled X/Y axis unit meters. SRS will ignore axis unit and be likely wrong.
```

**Comment by cristianlussana** [comment]
Hei,
Thanks for your feedback and the code. We will consider it when we plan the next release.
Best regards,
Cristian

**Comment by frafra** [comment]
Hei :)
is there any news on that? Could we keep the issue open until it is solved to make it easier to track existing issues?
